### ISSUE TITLE
error compiling the code 

### ISSUE THREAD

**Issue by NoxZZ** [SimonHu-HN/Wormhole_attack_in_ns3.29#1]
hey! I tried compiling the code in ns3.30.1 and it throws some errors

**Comment by SimonHu-HN** [comment]
Sorry, ns3.29 only. I haven't work on the NS3 a couple of months. I believe the NS3 vendor has changed some functions or modules, which causes the compiler to throw some errors. You could check the information of errors and aid by the official documentation to make my code active on NS 3.30.
